# Generated by Django 5.0.6 on 2024-06-03 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountInfo',
            fields=[
                ('AccountNumber', models.CharField(max_length=17, primary_key=True, serialize=False)),
                ('AccountType', models.CharField(max_length=100)),
                ('CurrentBalance', models.IntegerField(blank=True, null=True)),
                ('dateopened', models.DateTimeField()),
                ('ifsccode', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'account_info',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=200)),
                ('LastName', models.CharField(blank=True, max_length=200, null=True)),
                ('PhoneNumber', models.CharField(max_length=100)),
                ('DOB', models.DateField()),
                ('MailID', models.EmailField(blank=True, max_length=200, null=True)),
                ('Address', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='AccountTransaction',
            fields=[
                ('utr', models.CharField(max_length=22, primary_key=True, serialize=False)),
                ('transactiontype', models.CharField(max_length=4)),
                ('moneytransferred', models.IntegerField()),
                ('currentbalance', models.IntegerField(blank=True, null=True)),
                ('dateoftransaction', models.DateTimeField()),
                ('receivername', models.CharField(blank=True, max_length=200, null=True)),
                ('receiveraccountnumber', models.CharField(max_length=17)),
                ('receiverifsccode', models.CharField(max_length=11)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.accountinfo')),
                ('Status' , models.CharField(max_length=80 , default='SOME STRING'))
            ],
            options={
                'db_table': 'account_transaction',
            },
        ),
        migrations.AddField(
            model_name='accountinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
