# Generated by Django 5.0.5 on 2025-03-21 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountInfo',
            fields=[
                ('AccountNumber', models.CharField(max_length=17, primary_key=True, serialize=False)),
                ('AccountType', models.CharField(max_length=100)),
                ('CurrentBalance', models.IntegerField(blank=True, null=True)),
                ('dateopened', models.DateTimeField()),
                ('ifsccode', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'account_info',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=200)),
                ('LastName', models.CharField(blank=True, max_length=200, null=True)),
                ('PhoneNumber', models.CharField(max_length=100)),
                ('DOB', models.DateField()),
                ('MailID', models.EmailField(blank=True, max_length=200, null=True)),
                ('Address', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='AccountTransaction',
            fields=[
                ('utr', models.CharField(max_length=22, primary_key=True, serialize=False)),
                ('transactiontype', models.CharField(max_length=4)),
                ('moneytransfered', models.IntegerField(db_column='moneytransferred')),
                ('current_balance', models.IntegerField(blank=True, db_column='currentbalance', null=True)),
                ('dateoftransaction', models.DateTimeField()),
                ('receivername', models.CharField(blank=True, max_length=200, null=True)),
                ('receiveraccountnumber', models.CharField(max_length=17)),
                ('receiverifcscode', models.CharField(db_column='receiverifsccode', max_length=11)),
                ('Status', models.CharField(max_length=80)),
                ('accountnumber', models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.CASCADE, to='users.accountinfo')),
            ],
            options={
                'db_table': 'account_transaction',
            },
        ),
        migrations.AddField(
            model_name='accountinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
