# Generated by Django 5.0.5 on 2025-03-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_accountnumber_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounttransaction',
            old_name='account',
            new_name='accountnumber',
        ),
        migrations.AlterField(
            model_name='accounttransaction',
            name='transactiontype',
            field=models.CharField(max_length=4),
        ),
    ]
